#####################
### LOOK AND FEEL ###
#####################

# Fix crítico para el cursor en VMs
cursor {
    no_hardware_cursors = true
    min_refresh_rate = 60
}

general {
    gaps_in = 4
    gaps_out = 10
    border_size = 2
    col.active_border = $col_active
    col.inactive_border = $col_inactive
    layout = dwindle
    
    # Importante en VM: Si hay tearing, permite desactivar vsync
    allow_tearing = false 
}

decoration {
    rounding = 5 # Redondeo suave
    
    # SOMBRAS: Desactivadas o mínimas para ahorrar recursos
    shadow {
        enabled = false 
    }

    # BLUR: El asesino de rendimiento en VMs.
    # Lo mantenemos habilitado pero al MÍNIMO posible.
    blur {
        enabled = true
        size = 3
        passes = 1 # Mantenlo en 1 o 2 máximo. 3+ lagueará tu ratón.
        new_optimizations = true
        vibrancy = 0.1696
    }
}

animations {
    enabled = true
    # Animaciones más rápidas para sensación de fluidez ("snappy")
    bezier = fast, 0.15, 0, 0.1, 1
    animation = global, 1, 3, fast
    animation = workspaces, 1, 2, fast
    animation = windows, 1, 3, fast
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    # VFR es OBLIGATORIO en VM para que el host no trabaje en balde
    vfr = true 
}
