#################
### VARIABLES ###
#################

# --- Programas ---
$terminal    = kitty
$fileManager = dolphin
$menu        = rofi -show drun
$navegador   = firefox

# --- Tecla Modificadora ---
$mainMod = SUPER

# --- Colores ---
# Usamos variables para facilitar cambios de tema
$col_active      = rgba(33ccffee) rgba(00ff99ee) 45deg
$col_inactive    = rgba(595959aa)
$col_shadow      = rgba(1a1a1aee)
