##############################
### WINDOWS AND WORKSPACES ###
##############################

# Prevenir eventos de maximizado
windowrule = suppressevent maximize, class:.*

# Ventanas flotantes
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(qalculate-gtk)$

# Geometría y posición específica
windowrule = size 600 400, class:^(qalculate-gtk)$
windowrule = center, class:^(qalculate-gtk)$

# Regla "catch-all" para limpiar estado
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
