#############################
### ENVIRONMENT VARIABLES ###
#############################

# Cursores
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Backend y compatibilidad (XDG)
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

#################
### AUTOSTART ###
#################

# Sistema y UI
exec-once = waybar &
exec-once = hyprpaper &
exec-once = nm-applet --indicator &
exec-once = dunst &

# Autenticación (Polkit)
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
