#############
### INPUT ###
#############

input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    
    # En QEMU a veces la sensibilidad se siente "flotante". 
    # sensitivity 0 es raw input.
    sensitivity = 0 
    accel_profile = flat # Recomendado para VMs para consistencia con el host

    touchpad {
        natural_scroll = false
    }
}


